---
- name: Ajouter le repo Helm prometheus-community
  become: false
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

  environment:
    KUBECONFIG: /home/debian/.kube/config

- name: Mettre à jour les repos Helm
  become: false
  command: helm repo update
  environment:
    KUBECONFIG: /home/debian/.kube/config

- name: Créer le namespace monitoring
  kubernetes.core.k8s:
    name: "monitoring"
    api_version: v1
    kind: Namespace
    state: present
  environment:
    KUBECONFIG: /home/debian/.kube/config

- name: Installer Prometheus & Grafana
  become: false
  command: helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring 
  environment:
    KUBECONFIG: /home/debian/.kube/config

- name: Attendre que Prometheus soit prêt
  become: false
  command: kubectl rollout status deployment/kube-prometheus-stack-grafana -n monitoring --timeout=120s
  environment:
    KUBECONFIG: /home/debian/.kube/config
  changed_when: false
