---
- name: Désactiver le swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Supprimer le swap du fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
