---
- name: Préparer tous les nœuds
  hosts: all
  become: true
  roles:
    - common

- name: Installer k3s server
  hosts: control_plane
  become: true
  roles:
    - k3s_server

- name: Installer k3s agents
  hosts: workers
  become: true
  roles:
    - k3s_agent

- name: Installer les addons du cluster
  hosts: control_plane
  become: true
  roles:
    - argocd
