---
- name: Créer le répertoire .kube pour l'utilisateur debian
  file:
    path: /home/debian/.kube
    state: directory
    owner: debian
    group: debian
    mode: '0755'

- name: Copier le kubeconfig vers l'utilisateur debian
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/debian/.kube/config
    remote_src: true
    owner: debian
    group: debian
    mode: '0600'
